### ISSUE TITLE
synatax

### ISSUE THREAD

**Issue by santowhir** [freekmurze/analytics-reports#5]
All installed and running and I'm getting a

syntax error, unexpected '['

highlighting line:

return ['analytics-reports'];

Thanks

**Comment by wazirsoft** [comment]
Can you please paste the code which is giving you this error?

**Comment by santowhir** [comment]
All of your arrays are written $array = []; rather than $array = array();

I'd have to rewrite everything to get this working.

**Comment by santowhir** [comment]
Looks like it's my version of PHP.

https://github.com/JeffreyWay/Laravel-4-Generators/issues/4

Thanks.

**Comment by wazirsoft** [comment]
Yes you need to upgrade your version to 5.4 to make it work.

**Comment by santowhir** [comment]
Thank you.

**Comment by gaurav1992** [comment]
Hi 

My PHP Version 5.6.3 .and i have the same problem .Can you guys suggest what i have to do with it .

Thanks
